- name: Send mail
  uses: wadeww/send-email-action@master
  with:
    server_address: smtp.gmail.com
    port: 465
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    subject: Workflow finished
    body: Job completed ${{job.status}}
    to: sendjainabhi@gmail.com
    from: Abhishek
